name: drq
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - pytorch
  - cudatoolkit
  - absl-py
  - pyparsing
  - jupyterlab
  - scikit-image
  - pip:
    - termcolor
    - dm_control
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - pandas
    - ipdb
    - tqdm
    - torchvision
    - yapf
    - sklearn
    - matplotlib
    - kornia
